name: Deploy to Dev

on:
  issue_comment:
    types: [created]

jobs:
  deploy_dev:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'create-version')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Log GitHub Event
        run: echo "${{ toJson(github) }}"
      - name: Paca
        run: echo "Paca mundo"
